### ISSUE TITLE
gdb not fetching registers

### ISSUE THREAD

**Issue by wilhelmw201** [riscv/riscv-tools#311]
Hi,

I have been setting up the riscv toolchain on my computer, I have compiled the riscv-gnu-toolchain from https://github.com/riscv/riscv-gnu-toolchain and code from this repository, and have put them all in one folder.

On running the riscv-tests as described here https://github.com/riscv/riscv-tests/tree/master/debug  (I called make), I was able to pass some tests but fail in another bunch of tests: DebugBreakpoint, DebugSymbols, InterruptTest, Hwbp1/2, etc.
The failed tests gives mostly errors like this:
Could not fetch register "ft0"; remote failure reply 'E0E'
Could not fetch register "time"; remote failure reply 'E0E'
and so on.
I have also spotted a 
Error: Debugger is not authenticated to target Debug Module. (dmstatus=0x4c0c02). Use `riscv authdata_read` and `riscv authdata_write` commands to authenticate.

Is it that I have set up things incorrectly?

Thank you.

**Comment by jim-wilson** [comment]
riscv-tools is mostly unmaintained.  Try a git log in the riscv-tests dir and you will see that it contains a copy of riscv-tests from Sept 2018.  But if you do a git fetch and git log origin/master you will see riscv-tests has a last change from 2 days ago.  So the first step I would suggest is that you update to a recent version of riscv-tests.  Also, I'd suggest filing riscv-tests questions in the riscv-tests repo instead of the riscv-tools repo because they are more likely to be answered there.

riscv-gnu-toolchain is maintained but we don't have a dedicated gdb developer, so I don't know how well the gdb riscv-tests integration works, or how well it is being maintained.
